services:
  frontend:
    build:
      context: frontend
      target: development
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - react-express
    depends_on:
      - backend

  backend:
    restart: always
    build:
      context: backend
      target: development
    ports:
      - 4000:4000
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - react-express
    expose: 
      - 4000


networks:
  react-express: