version: '3.8'
services:
  frontend:
      build:
        context: frontend
        dockerfile: Dockerfile.prod
      environment: 
        - BACKEND_ENDPOINT=http://backend:4000/ 
        - BACKEND_PROXY=/api/
      ports:
        - 80:80
      command: /bin/bash -c "envsubst '$$BACKEND_ENDPOINT,$$BACKEND_PROXY' < /config/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
      restart: always
      networks:
        - react-express
      depends_on:
        - backend
  backend:
    restart: always
    build:
      context: backend
      dockerfile: Dockerfile.prod
    ports:
      - 4000:4000
    networks:
      - react-express
    expose: 
      - 4000

networks:
  react-express: